name: Auto Label Issues and Discussions

on:
  issues:
    types: [opened]
  discussion:
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues
        if: github.event_name == 'issues'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            needs-triage
      
      - name: Auto-label discussions
        if: github.event_name == 'discussion'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            needs-triage
