name: Mark and close stale issues and discussions

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 03:00 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            👋 This issue has been automatically marked as **stale** due to inactivity.
            If this is still important, please comment to keep it open.
            Otherwise, it will be closed in 7 days.
          close-issue-message: |
            🚫 Closing this issue due to prolonged inactivity. Feel free to reopen if it is still relevant.
          stale-pr-message: ""
          stale-issue-label: stale
          exempt-issue-labels: "pinned,security,discussion"
          days-before-stale: 30
          days-before-close: 7
          operations-per-run: 100
          stale-discussion-message: |
            👋 This discussion has been marked as **stale** due to inactivity.
            Please reply if this topic is still relevant!
          close-discussion-message: |
            🚫 This discussion is now closed due to inactivity. Feel free to reopen or start a new thread.
          days-before-stale-for-issues: 30
          days-before-close-for-issues: 7
          days-before-stale-for-prs: 30
          days-before-close-for-prs: 7
          days-before-stale-for-discussions: 30
          days-before-close-for-discussions: 7
