name: Welcome Newcomers

on:
  issues:
    types: [opened]
  discussion:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new issue creators
        if: github.event_name == 'issues'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Welcome to AuraXcapital Community!**
            Thank you for opening your first issue here. Please make sure to follow our issue templates and be as descriptive as possible.
            Need help? Ask in [Discussions](../discussions) or visit our [Telegram Community](https://t.me/aura_senti).
      - name: Greet new discussion creators
        if: github.event_name == 'discussion'
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          discussion-message: |
            👋 **Welcome to AuraXcapital Discussions!**
            Thanks for starting your first discussion. This is the place to share ideas, ask questions, or connect with the community.
            Before posting, check our [README](../README.md) for contribution tips!
